# System configuration
voting:
  promotion_threshold: 5 # Votes required for agent promotion
  demotion_threshold: -3 # Reputation threshold for demotion
  demote_multiplier: 2 # Demote vote weight multiplier
  self_vote_weight: 0.2 # Self-vote weight factor
  binder_vote_multiplier: 1.5 # BINDER vote weight multiplier

  # Reputation-based vote weighting
  reputation_weight:
    enabled: true
    min_rep_for_full_weight: -2.0 # Reputation threshold for full weight
    scale: 0.08 # Weight reduction scale factor

  # Dynamic threshold adjustment
  dynamic_threshold:
    enabled: false
    threshold_increase: 1 # Threshold increase amount
    cooldown_tickets: 10 # Cooldown duration in tickets
    triggers: ["PROMOTION", "DEMOTION"] # Triggering events

  # Self-vote cooldown system
  self_vote_cooldown:
    enabled: false
    cooldown_tickets: 4 # Cooldown duration in tickets
    reduced_weight: 0.1 # Reduced weight factor

# AI model settings
ai:
  model: "gpt-4o-mini" # OpenAI model
  max_tokens: 80 # Response token limit
  temperature: 0.7 # Response variability
  timeout: 15 # API timeout seconds
  token_budget: 3000 # Context token limit

# Civil gate configuration
civil_gate:
  toxicity_threshold: 0.7 # Toxicity detection threshold
  use_openai_moderation: true
  reputation_penalty: 0.6 # Gate violation penalty
  fallback_patterns:
    - "waste of space"
    - "pathetic"

# Rate limiting
rate_limiting:
  enabled: true
  window_seconds: 120 # Time window duration
  max_messages: 10 # Message limit per window

# Experiment timing
timing:
  message_interval: 1.5 # Base message interval
  jitter_range: 0.5 # Timing variance range
  auto_stop_tickets: null # Auto-stop threshold

# semantic binding
dsbl:
  civil_binding:
    probabilistic_injection_rate: 0.0

# Probation system
probation:
  enabled: false
  block_duration_tickets: 4 # Probation duration
  reentry_jitter: 1 # Reentry timing variance
  forbid_votes_only: true # Block voting only
  on_reentry_reputation_gain: 0.5 # Reentry reputation bonus
  exempt_agents: [] # Exempt agent list

# BIND gate management
bind_gates:
  cooldown_tickets: 10 # BIND usage cooldown
  default_ttl_tickets: 50 # Default effect duration
  auto_bind_probability: 0.20 # Auto-activation probability

# Adaptive response system
adaptive_immune:
  enable_reflect: true # Pressure detection
  enable_calibrate: true # Frequency adjustment

# Agent personalities
personalities:
  supportive:
    voting_frequency: 0.87 # Supportive behavior frequency
  technical:
    voting_frequency: 0.85 # Analytical behavior frequency
  strategic:
    voting_frequency: 0.75 # Strategic behavior frequency
  follower:
    voting_frequency: 0.9 # Following behavior frequency
  contrarian:
    voting_frequency: 0.26 # Contrarian behavior frequency
  malice:
    voting_frequency: 0.9 # Antagonist behavior frequency

# Audit logging
audit:
  console_output: true # Console output enabled
  jsonl_logging: true # JSONL file logging
  include_content_hash: true # Content hashing enabled

  # Metrics mode settings
  metrics_data_mode: false # Metrics mode enabled
  metrics_gate_decisions: false # Gate decision logging
  metrics_vote_calculations: false # Vote calculation logging
  metrics_state_changes: false # State change logging
  metrics_timing: false # Timing information logging

# Security settings
security:
  defense_in_depth: true # Multi-layer validation enabled
  dangerous_patterns:
    - "rm -rf"
    - "system("
    - "eval("
    - "exec("
    - "__import__"
    - "subprocess"
    - "os.system"
    - "password"
    - "token"
    - "secret"
    - "api_key"
